name: C CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-valgrind:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Ensure that build tools and Valgrind are installed
      - name: Install build tools and Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential valgrind

      # Build everything from the makefile
      - name: Build
        run: make clean && make all

      # SKIPPING FOR NOW - REINSTATE ONCE FULL EXECUTABLES ARE READY
      # # Run program/tests under Valgrind
      # - name: Run under Valgrind (memory leak check)
      #   run: |
      #     valgrind \
      #       --leak-check=full \
      #       --show-leak-kinds=all \
      #       --track-origins=yes \
      #       --error-exitcode=1 \
      #       ./run_tests
